### ISSUE TITLE
Depend on latest stable and remove Babel

### ISSUE THREAD

**Issue by kahlil** [reactivepod/fido#11]
How about we depend on the latest stable version of Node and just use the ES6 capabilities that are currently in there? A lot of ES6 features have landed in Node: https://nodejs.org/en/docs/es6/

**Comment by cilice** [comment]
On IRC Kahlil and Henning were both okay do downgrade to ^5.8 until someone manages to reproduce the same setup.

**Comment by kahlil** [comment]
Oh yeah, this is actually closed since a while :)
