### ISSUE TITLE
Sane default configuration

### ISSUE THREAD

**Issue by hglattergotz** [reactivepod/fido#2]
At this point the application will fail after installation because of a missing configuration.js file.
Make this more elegant by doing one of the following:
 * Return an error message with instructions on what to do to get setup correctly
 * Install a default configuration
 * Implement an init command that helps with generating an initial configuration

**Comment by kahlil** [comment]
my suggestion: 
- throw away the need for `configuration.js`
- hard code the default countries (all)
- make the podcast ID and the podcast name required to be passed on the cli
- make an optional cli argument that allows to set a custom list of countries

**Comment by hglattergotz** [comment]
The idea behind configuration.js or something similar is that as a user you will probably never or rarely change that so it would be a pain to have to specify this on every run.

What do you think of this:
In addition to 1, 3 and 4 of the points you mentioned above allow the user to have a ~/.fido that contains the desired values for id(s), name(s) and countries so they do not have to be passed every time.

**Comment by kahlil** [comment]
Sounds good! Let's do that.
