### ISSUE TITLE
Introduce semantic-release

### ISSUE THREAD

**Issue by kahlil** [reactivepod/fido#52]
https://github.com/semantic-release/semantic-release

**Comment by cilice** [comment]
Uhm, don't you mean https://github.com/semantic-release/semantic-release?

**Comment by kahlil** [comment]
lol yes

**Comment by cilice** [comment]
Done. :) Now, we have to stick to https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md when writing commit messages.

**Comment by kahlil** [comment]
fantastic! thank you
