### ISSUE TITLE
Implement commitizen?

### ISSUE THREAD

**Issue by cilice** [reactivepod/fido#53]
Since we use semantic-release now, it would make sense to make angularjs style git commits easier. We can have it: https://github.com/commitizen/cz-cli

![Example](https://raw.githubusercontent.com/commitizen/cz-cli/master/meta/screenshots/add-commit.png)

Yay or nay?

**Comment by cilice** [comment]
Since it doesn't interfere with anything, I just added the config it to the package.json, you don't have to use it.

**Comment by kahlil** [comment]
+1
